//! Claude Code transcript adapter.
//!
//! Covers both surfaces: the `claude` CLI and the VS Code extension. The
//! extension is `anthropic.claude-code` - the same program with a different
//! front end - so it writes the same transcripts to the same place and needs no
//! separate reader. Verified against the `anthropic.claude-code` VS Code
//! extension, which writes the same transcripts as the CLI.
//!
//! One JSON object per line under `~/.claude/projects/<project>/<uuid>.jsonl`.
//! Only the fields this tool needs are modelled; the format carries a great deal
//! more, and binding to all of it would break on every release.
//!
//! Field shapes verified against real transcripts before writing this:
//!
//! - tool calls live in `message.content[]` where `type == "tool_use"`, carrying
//!   `id`, `name` and `input`
//! - results come back as `type == "tool_result"` with `tool_use_id` and
//!   `is_error`; the failing call is found by pairing the two ids, since the
//!   result itself does not name the tool
//! - `message.usage` holds the token counts
//!
//! **The query boundary is the one thing likely to be wrong here.** A record with
//! `type == "user"` is not necessarily a user speaking: tool results, slash
//! command output, caveat blocks and system reminders all arrive the same way. A
//! naive count returned 193 "queries" for a session with roughly fourteen. The
//! filter in `is_real_user_message` is therefore conservative, and has its own
//! tests.

use std::fs;
use std::path::{Path, PathBuf};
use std::time::UNIX_EPOCH;

use anyhow::{Context, Result};
use serde_json::Value;

use crate::model::{Query, Session, Step};

/// Where a dispatched tool call landed, so its result can find it again.
struct PendingCall {
    query: usize,
    step: usize,
    tool: String,
    target: Option<String>,
}
use crate::source::Source;

/// Wrapper tags that mean the text was generated by the harness, not typed.
const SYNTHETIC_PREFIXES: &[&str] = &[
    "<local-command-caveat>",
    "<command-name>",
    "<command-message>",
    "<local-command-stdout>",
    "<system-reminder>",
    "<user-prompt-submit-hook>",
    "[SYSTEM NOTIFICATION",
    "Caveat: The messages below",
];

pub fn transcripts_root() -> PathBuf {
    // `dirs` would pull a crate for one lookup. HOME on unix, USERPROFILE on
    // Windows, which is what the crate would consult anyway.
    let home = std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .map(PathBuf::from)
        .unwrap_or_default();
    home.join(".claude").join("projects")
}

/// Every transcript on disk, newest last.
pub fn discover(root: &Path) -> Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    let Ok(projects) = fs::read_dir(root) else {
        return Ok(out); // no transcripts yet is not an error
    };
    for project in projects.flatten() {
        if !project.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            continue;
        }
        let Ok(files) = fs::read_dir(project.path()) else {
            continue;
        };
        for f in files.flatten() {
            let p = f.path();
            if p.extension().is_some_and(|e| e == "jsonl") {
                out.push(p);
            }
        }
    }
    out.sort_by_key(|p| mtime(p));
    Ok(out)
}

fn mtime(p: &Path) -> u64 {
    fs::metadata(p)
        .and_then(|m| m.modified())
        .ok()
        .and_then(|t| t.duration_since(UNIX_EPOCH).ok())
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// True when a `user` record is a person typing rather than harness output.
pub fn is_real_user_message(content: &str) -> bool {
    let t = content.trim_start();
    if t.is_empty() {
        return false;
    }
    !SYNTHETIC_PREFIXES.iter().any(|p| t.starts_with(p))
}

/// Parse one transcript. Malformed lines are skipped, never fatal - a truncated
/// or half-written file is normal when a session is still running, and refusing
/// to read it would make the tool fail exactly while it is most wanted.
pub fn parse(path: &Path) -> Result<Session> {
    let text = fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;

    let mut session = Session {
        id: path
            .file_stem()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_default(),
        project: path
            .parent()
            .and_then(|p| p.file_name())
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_default(),
        mtime: mtime(path),
        queries: Vec::new(),
    };

    // tool_use id -> exactly which step it created. The result arrives on a
    // later line and identifies the call only by id, so the id must carry
    // through to the step - not merely to the tool name.
    //
    // Marking "the last unfailed step with a matching tool name" instead is
    // wrong, and wrong in the common case: Claude Code issues tool calls in
    // parallel batches. Given `git show ...` and `ls /tmp` dispatched together
    // and only the git call failing, the name-based search marked `ls` and the
    // frozen opportunity key became `Bash:ls /tmp` for a git error. Every
    // number downstream - the effect denominator, the MCP warning - inherited
    // that. Reproduced before this fix, and covered by a test below.
    let mut pending: std::collections::HashMap<String, PendingCall> =
        std::collections::HashMap::new();
    let mut step_idx = 0usize;

    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let Ok(v) = serde_json::from_str::<Value>(line) else {
            continue;
        };

        let kind = v.get("type").and_then(Value::as_str).unwrap_or("");
        let message = v.get("message");

        if kind == "user" {
            // Content is a string for plain text, but an array of blocks when
            // the message carries an image or was composed by a client that
            // always uses block form. Only handling the string case dropped the
            // query *and every step in it*, because steps are only recorded
            // once a query exists - whole sessions could go dark.
            let text: Option<String> = message.and_then(|m| m.get("content")).and_then(|c| {
                match c {
                    Value::String(s) => Some(s.clone()),
                    Value::Array(items) => {
                        let joined: String = items
                            .iter()
                            // A tool_result is not a person speaking.
                            .filter(|i| {
                                i.get("type").and_then(Value::as_str) != Some("tool_result")
                            })
                            .filter_map(|i| i.get("text").and_then(Value::as_str))
                            .collect::<Vec<_>>()
                            .join("\n");
                        (!joined.trim().is_empty()).then_some(joined)
                    }
                    _ => None,
                }
            });
            if let Some(s) = text.as_deref() {
                if is_real_user_message(s) {
                    session.queries.push(Query {
                        idx: session.queries.len(),
                        text: s.chars().take(400).collect(),
                        ..Default::default()
                    });
                }
            }
        }

        // Usage is attributed to the query in flight. Records arriving before any
        // user message belong to no query and are dropped rather than invented.
        if let Some(usage) = message.and_then(|m| m.get("usage")) {
            if let Some(q) = session.queries.last_mut() {
                for k in [
                    "input_tokens",
                    "cache_creation_input_tokens",
                    "cache_read_input_tokens",
                    "output_tokens",
                ] {
                    q.tokens += usage.get(k).and_then(Value::as_u64).unwrap_or(0);
                }
            }
        }

        let Some(items) = message
            .and_then(|m| m.get("content"))
            .and_then(Value::as_array)
        else {
            continue;
        };

        for item in items {
            match item.get("type").and_then(Value::as_str) {
                Some("tool_use") => {
                    let id = item
                        .get("id")
                        .and_then(Value::as_str)
                        .unwrap_or("")
                        .to_string();
                    let name = item
                        .get("name")
                        .and_then(Value::as_str)
                        .unwrap_or("?")
                        .to_string();
                    let input = item.get("input");
                    let target = input
                        .and_then(|i| {
                            i.get("file_path")
                                .or_else(|| i.get("command"))
                                .or_else(|| i.get("pattern"))
                        })
                        .and_then(Value::as_str)
                        .map(|s| s.chars().take(200).collect::<String>());

                    if let Some(q) = session.queries.last_mut() {
                        q.steps.push(Step {
                            idx: step_idx,
                            tool: name.clone(),
                            target: target.clone(),
                            failed: false,
                            error: None,
                        });
                    }
                    // Record where the step landed, so its result can find it
                    // again regardless of what else was dispatched alongside.
                    if let Some(qi) = session.queries.len().checked_sub(1) {
                        let si = session.queries[qi].steps.len() - 1;
                        pending.insert(
                            id,
                            PendingCall {
                                query: qi,
                                step: si,
                                tool: name,
                                target,
                            },
                        );
                    } else {
                        // A call before any user message belongs to no query.
                        // Keep the identity so a later result is attributed to
                        // the right tool rather than to the first query that
                        // happens to appear.
                        pending.insert(
                            id,
                            PendingCall {
                                query: usize::MAX,
                                step: 0,
                                tool: name,
                                target,
                            },
                        );
                    }
                    step_idx += 1;
                }
                Some("tool_result") => {
                    if item.get("is_error").and_then(Value::as_bool) != Some(true) {
                        continue;
                    }
                    let id = item
                        .get("tool_use_id")
                        .and_then(Value::as_str)
                        .unwrap_or("");
                    let Some(call) = pending.remove(id) else {
                        // A result with no matching call - a truncated file, or
                        // a call made before this transcript began. Guessing
                        // which step it belongs to is what produced the bug
                        // above, so drop it rather than attribute it wrongly.
                        continue;
                    };
                    let err = item
                        .get("content")
                        .map(stringify_content)
                        .unwrap_or_default();

                    // Mark the exact step this result belongs to. The lookup is
                    // by index, so a parallel batch cannot cross-attribute.
                    if let Some(step) = session
                        .queries
                        .get_mut(call.query)
                        .and_then(|q| q.steps.get_mut(call.step))
                    {
                        step.failed = true;
                        step.error = Some(err);
                    } else if let Some(q) = session.queries.last_mut() {
                        // The call predates the first user message, so it has no
                        // step. Record it with its own identity rather than
                        // borrowing another call's.
                        q.steps.push(Step {
                            idx: step_idx,
                            tool: call.tool,
                            target: call.target,
                            failed: true,
                            error: Some(err),
                        });
                        step_idx += 1;
                    }
                }
                _ => {}
            }
        }
    }

    Ok(session)
}

/// Tool result content is sometimes a string, sometimes a list of blocks.
fn stringify_content(v: &Value) -> String {
    match v {
        Value::String(s) => s.clone(),
        Value::Array(items) => items
            .iter()
            .filter_map(|i| i.get("text").and_then(Value::as_str))
            .collect::<Vec<_>>()
            .join("\n"),
        other => other.to_string(),
    }
}

/// Claude Code: the `claude` CLI and the VS Code extension, one format.
pub struct ClaudeCode;

impl Source for ClaudeCode {
    fn name(&self) -> &'static str {
        "claude-code"
    }
    fn root(&self) -> PathBuf {
        transcripts_root()
    }
    fn discover(&self) -> Result<Vec<PathBuf>> {
        discover(&self.root())
    }
    fn parse(&self, path: &Path) -> Result<Session> {
        parse(path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_harness_generated_user_records() {
        // Every one of these appears as `type: "user"` in real transcripts, and
        // counting them as questions produced 193 queries for a 14-query session.
        assert!(!is_real_user_message("<local-command-caveat>Caveat: ..."));
        assert!(!is_real_user_message("<command-name>/login</command-name>"));
        assert!(!is_real_user_message(
            "<system-reminder>note</system-reminder>"
        ));
        assert!(!is_real_user_message(
            "[SYSTEM NOTIFICATION - NOT USER INPUT]"
        ));
        assert!(!is_real_user_message("   "));
    }

    #[test]
    fn accepts_a_person_typing() {
        assert!(is_real_user_message("fix the budget truncation"));
        assert!(is_real_user_message("  why is this failing?"));
        // A question that merely mentions a tag is still a person.
        assert!(is_real_user_message("what does <system-reminder> mean?"));
    }

    #[test]
    fn parallel_calls_do_not_cross_attribute() {
        // Reproduces the defect this parser had: two Bash calls dispatched
        // together, only the first fails, and the failure was marked on the
        // second because the search was by tool name rather than by id. The
        // frozen opportunity key became `Bash:ls /tmp` for a git error.
        let dir = std::env::temp_dir().join(format!("anomalift-attr-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("s.jsonl");
        std::fs::write(&path, concat!(
            r#"{"type":"user","message":{"content":"fix the git flags"}}"#, "\n",
            r#"{"type":"assistant","message":{"content":[{"type":"tool_use","id":"A","name":"Bash","input":{"command":"git show --name-only -s HEAD"}},{"type":"tool_use","id":"B","name":"Bash","input":{"command":"ls /tmp"}}]}}"#, "\n",
            r#"{"type":"user","message":{"content":[{"type":"tool_result","tool_use_id":"A","is_error":true,"content":"fatal: options cannot be used together"}]}}"#, "\n",
        )).unwrap();

        let session = parse(&path).unwrap();
        let failed: Vec<&Step> = session.failures().collect();
        assert_eq!(failed.len(), 1, "exactly one call failed");
        assert_eq!(
            failed[0].target.as_deref(),
            Some("git show --name-only -s HEAD"),
            "the failure must be attributed to the call that produced it"
        );
        // And the innocent call must remain unmarked.
        let all: Vec<&Step> = session.steps().collect();
        let ls = all
            .iter()
            .find(|s| s.target.as_deref() == Some("ls /tmp"))
            .unwrap();
        assert!(
            !ls.failed,
            "a sibling call in the same batch must not be blamed"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn stringifies_both_content_shapes() {
        let s = serde_json::json!("plain error");
        assert_eq!(stringify_content(&s), "plain error");
        let blocks = serde_json::json!([{ "type": "text", "text": "line one" }]);
        assert_eq!(stringify_content(&blocks), "line one");
    }
}
